
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BUTTON CHECK COMMA CURL_L CURL_R IDENTIFIER IMAGE LABEL LINE MAKEWINDOW NUMBER OVAL PERIOD RESET SQUARE STARTexpression : START CURL_L NUMBER COMMA NUMBER CURL_Rexpression : IDENTIFIER PERIOD LABELexpression : MAKEWINDOWexpression : CHECKexpression : BUTTON  CURL_L NUMBER COMMA NUMBER COMMA NUMBER COMMA NUMBER CURL_Rexpression : OVAL CURL_L NUMBER COMMA NUMBER COMMA NUMBER COMMA NUMBER CURL_Rexpression : SQUARE CURL_L NUMBER COMMA NUMBER COMMA NUMBER COMMA NUMBER CURL_Rexpression : RESETexpression : LINE CURL_L NUMBER COMMA NUMBER COMMA NUMBER COMMA NUMBER CURL_Rexpression : IMAGE CURL_L IDENTIFIER PERIOD IDENTIFIER CURL_R'
    
_lr_action_items = {'START':([0,],[2,]),'IDENTIFIER':([0,18,31,],[3,25,37,]),'MAKEWINDOW':([0,],[4,]),'CHECK':([0,],[5,]),'BUTTON':([0,],[6,]),'OVAL':([0,],[7,]),'SQUARE':([0,],[8,]),'RESET':([0,],[9,]),'LINE':([0,],[10,]),'IMAGE':([0,],[11,]),'$end':([1,4,5,9,20,38,43,56,57,58,59,],[0,-3,-4,-8,-2,-1,-10,-5,-6,-7,-9,]),'CURL_L':([2,6,7,8,10,11,],[12,14,15,16,17,18,]),'PERIOD':([3,25,],[13,31,]),'NUMBER':([12,14,15,16,17,26,27,28,29,30,39,40,41,42,48,49,50,51,],[19,21,22,23,24,32,33,34,35,36,44,45,46,47,52,53,54,55,]),'LABEL':([13,],[20,]),'COMMA':([19,21,22,23,24,33,34,35,36,44,45,46,47,],[26,27,28,29,30,39,40,41,42,48,49,50,51,]),'CURL_R':([32,37,52,53,54,55,],[38,43,56,57,58,59,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> START CURL_L NUMBER COMMA NUMBER CURL_R','expression',6,'p_init_frame','U-GUI Parser.py',9),
  ('expression -> IDENTIFIER PERIOD LABEL','expression',3,'p_stunWarning','U-GUI Parser.py',26),
  ('expression -> MAKEWINDOW','expression',1,'p_make_window','U-GUI Parser.py',32),
  ('expression -> CHECK','expression',1,'p_check','U-GUI Parser.py',38),
  ('expression -> BUTTON CURL_L NUMBER COMMA NUMBER COMMA NUMBER COMMA NUMBER CURL_R','expression',10,'p_CreateButton','U-GUI Parser.py',47),
  ('expression -> OVAL CURL_L NUMBER COMMA NUMBER COMMA NUMBER COMMA NUMBER CURL_R','expression',10,'p_CreateCircle','U-GUI Parser.py',55),
  ('expression -> SQUARE CURL_L NUMBER COMMA NUMBER COMMA NUMBER COMMA NUMBER CURL_R','expression',10,'p_CreateSquare','U-GUI Parser.py',66),
  ('expression -> RESET','expression',1,'p_ResetShapes','U-GUI Parser.py',76),
  ('expression -> LINE CURL_L NUMBER COMMA NUMBER COMMA NUMBER COMMA NUMBER CURL_R','expression',10,'p_CreateLine','U-GUI Parser.py',89),
  ('expression -> IMAGE CURL_L IDENTIFIER PERIOD IDENTIFIER CURL_R','expression',6,'p_LoadImage','U-GUI Parser.py',99),
]
